--DEMOMEMBE TABLE 생성 쿼리
CREATE TABLE DEMOMEMBER(
	ID VARCHAR2(50) NOT NULL,
	PW VARCHAR2(300) NOT NULL,
	NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) NOT NULL,
	PHONE VARCHAR2(50) NOT NULL,
	AUTH VARCHAR2(20) NOT NULL,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "DEMOMEMBER_PK" PRIMARY KEY (ID)
);



--DEMOMEMBER 암호화 전 더미 테이블 회원생성(ROLE_USER) 쿼리
INSERT INTO DEMOMEMBER (ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO05', '1234', 'DEMO05', 'DEMO05@gmail.com', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);
--DEMOMEMBER 암호화 전 더미 테이블 회원생성(ROLE_ADMIN) 쿼리
INSERT INTO DEMOMEMBER (ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('ADMIN', '1234', 'ADMIN', 'ADMIN@gmail.com', '010-1234-5678', 'ROLE_ADMIN', 'N', SYSDATE);


-------DEMOMEMBER_STATEMENT QUERY-------
--(1) DEMOMEMBER 회원 전체조회 쿼리 (등록일순 내림차순)
SELECT ID, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE
	FROM DEMOMEMBER 
		ORDER BY REGDATE DESC;
--(2) DEMOMEMBER 회원가입 쿼리 
INSERT INTO DEMOMEMBER (ID, PW, NAME, EMAIL, PHONE, AUTH, DELFLAG, REGDATE)
VALUES('DEMO05', '1234', 'DEMO05', 'DEMO05@gmail.com', '010-1234-5678', 'ROLE_USER', 'N', SYSDATE);	
--(3) DEMOMEMBER 로그인(아이디, 비밀번호, 사용여부='N') 쿼리
SELECT ID, NAME, EMAIL, PHONE, AUTH, REGDATE
	FROM DEMOMEMBER WHERE ID='DEMO01' AND PW='1234' AND DELFLAG='N';
-------------------------------------------------------

--DEMOBOARD TABLE 생성 쿼리
CREATE TABLE DEMOBOARD(
	SEQ NUMBER,
	ID VARCHAR2(50) NOT NULL,
	TITLE VARCHAR2(200) NOT NULL,
	CONTENT VARCHAR2(4000),
	STEP NUMBER NOT NULL,
	DEPTH NUMBER NOT NULL,
	REFER NUMBER NOT NULL,
	READCOUNT NUMBER,
	DELFLAG CHAR(1) NOT NULL,
	REGDATE DATE NOT NULL,
	CONSTRAINT "DEMOBOARD_PK" PRIMARY KEY (SEQ),
	CONSTRAINT "DEMOBOARD_FK" FOREIGN KEY ("ID") REFERENCES DEMOMEMBER ("ID")
);

--DEMOBOARD_SEQ SEQ 1씩 증가 쿼리
CREATE SEQUENCE DEMOBOARD_SEQ START WITH 1 INCREMENT BY 1;

-------DEMOBOARD_STATEMENT QUERY-------
--(1) DEMOBOARD 게시판 새글 쓰기
INSERT INTO DEMOBOARD  (SEQ, ID, TITLE, 
            											CONTENT, STEP, "DEPTH" ,
            											REFER, READCOUNT, DELFLAG , REGDATE)
      VALUES(DEMOBOARD_SEQ.NEXTVAL , 'DEMO03', DEMOBOARD_SEQ.CURRVAL||'번째 새 글 TITLE',
          				DEMOBOARD_SEQ.CURRVAL||'번째 새 글 CONTENT', 0, 0, 
          				(SELECT NVL(MAX(REFER),0) +1 FROM SPRINGBOARD s), 0,'N',SYSDATE);
          			
INSERT INTO DEMOBOARD (SEQ, ID, TITLE, CONTENT, STEP, "DEPTH", REFER, READCOUNT, DELFLAG, REGDATE)
	VALUES (DEMOBOARD_SEQ.NEXTVAL, 'DEMO01', 'DEMO01 새글입력 TEST', 'DEMO01 새글입력 TEST 내용입니다.', 0, 0, (SELECT NVL(MAX(REFER),0)+1 FROM DEMOBOARD), 0, 'N', SYSDATE);
          			
SELECT COUNT(*) FROM DEMOBOARD;          	
SELECT * FROM DEMOBOARD d ;

--(2) DEMOBOARD 게시판 전체 조회 (관리자/사용자)

SELECT SEQ, ID, LPAD(TITLE, LENGTH(TITLE)+"DEPTH"*10) , STEP, DEPTH, REFER, DELFLAG,READCOUNT , REGDATE
 FROM DEMOBOARD  WHERE DELFLAG ='N' 
    ORDER BY REFER DESC, STEP ASC;

   SELECT SEQ, ID, TITLE, STEP, "DEPTH" , REFER , DELFLAG , READCOUNT , REGDATE 
   	FROM DEMOBOARD WHERE DELFLAG ='N' ORDER BY REFER DESC, STEP ASC;
   
   --(3) DEMOBOARD 게시판 상세 조회 
 SELECT SEQ, ID, TITLE, CONTENT, REFER, STEP, DEPTH, DELFLAG,READCOUNT , REGDATE
	FROM DEMOBOARD 
	 WHERE SEQ = '3';

-------------------------------------------------------
--DEMOFILE TABLE 생성 쿼리
CREATE TABLE DEMOFILE(
	FILE_SEQ NUMBER,
	DEMOBOARD_SEQ NUMBER NOT NULL, 
	ORIGINAL_FILE_NAME VARCHAR2(260) NOT NULL,
	STORED_FILE_NAME VARCHAR2(36) NOT NULL,
	FILE_PATH NUMBER,
	REGDATE DATE DEFAULT SYSDATE NOT NULL,
	DEL_GB VARCHAR2(1) DEFAULT 'N' NOT NULL,
	CONSTRAINT "DEMOFILE_PK" PRIMARY KEY (FILE_SEQ),
	CONSTRAINT "DEMOFILE_FK" FOREIGN KEY ("DEMOBOARD_SEQ") REFERENCES DEMOBOARD ("SEQ")
);
   	
CREATE SEQUENCE DEMOFILE_FILE_SEQ START WITH 1 INCREMENT BY 1 NOCACHE;

--(1)DEMOFILE 새로 추가 쿼리
INSERT INTO DEMOFILE
(FILE_SEQ, DEMOBOARD_SEQ, ORIGINAL_FILE_NAME, STORED_FILE_NAME, FILE_PATH, REGDATE, DEL_GB)
VALUES(DEMOFILE_FILE_SEQ.NEXTVAL , 1, 'HI', 'DSS', 'C:\eclipse_web_2020_09\workspace_web\20220508_DemoProject', SYSDATE , 'N' );

SELECT *
	FROM DEMOFILE d  ;
